version: "3.3"

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: postgres://ririn:ririntobrut@db:5432/ririnbimadb?sslmode=disable
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ririn
      POSTGRES_PASSWORD: ririntobrut
      POSTGRES_DB: ririnbimadb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
